### ISSUE TITLE
model load mismatch

### ISSUE THREAD

**Issue by KennyAtDM** [ZhengPeng7/BiRefNet#28]
In inference.py, how to load different models other then BiRefNet-massive-epoch_240.pth?
I keep getting RuntimeError: Error(s) in loading state_dict for BiRefNet, but do not know where to set the models weights correctly

      for weights in weights_lst:
          print(weights.strip('.pth').split('epoch_')[-1])
          if int(weights.strip('.pth').split('epoch_')[-1]) % 1 != 0:
              continue
          print('\tInferencing {}...'.format(weights))
          state_dict = torch.load(weights, map_location='cpu')
          state_dict = check_state_dict(state_dict)
          model.load_state_dict(state_dict)
          model = model.to(device)

**Comment by ZhengPeng7** [comment]
If the error is in loading the weights (key or weights mismatch), plz tell me.

**Comment by KennyAtDM** [comment]
> If the error is in loading the weights (key or weights mismatch), plz tell me.

Yes, the error is in loading weights, when if I remove the if

**Comment by KennyAtDM** [comment]
I am trying to load BiRefNet-massive-bb_swin_v1_tiny-epoch_235.pth rather than BiRefNet-massive-epoch_240.pth

**Comment by ZhengPeng7** [comment]
Hi, @KennyAtDM , I checked the weights loading as below, which seems alright:

![截屏2024-06-07 09 04 05](https://github.com/ZhengPeng7/BiRefNet/assets/25921713/c8da59cb-72fb-46f7-9ec1-730c18fb3cb6)

I guess the key is that: if you want to load the weights with a certain backbone, you need to first set the `bb` in `config.py` to the corresponding one, so that `BiRefNet()` could be the right one you want. Have a try it.

Tell me if there is still any problem :)

**Comment by ZhengPeng7** [comment]
Re-open it if you still have this problem.

**Comment by karndeb** [comment]
@ZhengPeng7 I am still having the same issue. I changed the self.bb value in the conf but still not working. Can you help?

**Comment by ZhengPeng7** [comment]
Hi, of course, I can help make sure everything is good; it's my job and my duty.

But the codes you use are exactly the same as mine. Therefore, the problem is most probably related to the environment. Can you create a new env with py=3.9 and torch==2.0.1 as the guideline in README? Only [two steps](https://github.com/ZhengPeng7/BiRefNet#environment-setup). Tell me if it works in the new env.

**Comment by ZhengPeng7** [comment]
Thanks, @MinGiSa, for the help. Sorry, @karndeb, my mistake, you had the try on the colab, so there's no problem with the env. And I also did the test in the colab just now for single image inference, as shown below; everything is good for loading the version with swin_v1_t as the backbone, as shown below.
**BTW, did you restart the session to load the updated `self.bb` in `config.py`?** You can print the `Config().bb` to test it.
![截屏2024-06-17 22 39 35](https://github.com/ZhengPeng7/BiRefNet/assets/25921713/94679246-10e2-428f-b077-c675d9a23262)

**Comment by karndeb** [comment]
@ZhengPeng7 and @MinGiSa . Its working perfectly now. Thanks for the quick response. I had changed the config from 6 to 3 in the self.bb but I think I didnt restart the session. Btw, absolutley brilliant work. Very impressive. This can be closed now.

**Comment by ZhengPeng7** [comment]
Great, glad to hear that.
