### ISSUE TITLE
Crash when loading more than 7000 images

### ISSUE THREAD

**Issue by schirrmacher** [ZhengPeng7/BiRefNet#33]
When I execute your training script I get a crash after loading roughly 7000 images:

` % ./train.sh humans
Training started at Fri Jul 12 17:08:00 CEST 2024
Single-GPU mode received...
2024-07-12 17:08:05,770 INFO datasets: load_all=True, compile=True.
2024-07-12 17:08:05,770 INFO Other hyperparameters:
2024-07-12 17:08:05,771 INFO Namespace(resume='ckpt/xx/ep100.pth', epochs=150, trainset='DIS5K', ckpt_dir='ckpt/humans', testsets='NO', dist=False)
batch size: 4
Not exists: /home/macher/datasets/dis/humans/training/gt/desktop.JPEG
 41%|███████████████████████████████████████████████▋                                                                     | 7032/17238 [02:28<05:57, 28.55it/s]./train.sh: line 40: 1324513 Killed                  CUDA_VISIBLE_DEVICES=${devices} python train.py --ckpt_dir ckpt/${method} --epochs ${epochs} --testsets ${testsets} --dist ${to_be_distributed} --resume ckpt/xx/ep100.pth
Training finished at Fri Jul 12 17:10:35 CEST 2024`

Do you have any recommendations around memory? I am using Nvidia 4090 and have 64GB of RAM.

**Comment by ZhengPeng7** [comment]
Hi, your problem is in two perspectives of the device:

1. GPU memory: as I mentioned in README, the default training setting is for A100-80G now. So, you may need to decrease the batch size or use smaller backbones (e.g., swin_v1_tiny, pvt_v2_b2...). 4090 has only 24G GPU memory, so I suggest trying with a smaller backbone.

2. CPU memory: I loaded all the images into memory for some faster IO during training, which, though, costs a lot of RAM. But you can also set the `load_all=False` in `config.py` to skip loading all samples before training.

Tell me if you still have issues on this :)

**Comment by ZhengPeng7** [comment]
BTW, you should also surely set `load_all=False` when doing debug.

**Comment by ZhengPeng7** [comment]
I personally don't recommend using that one. That's not my account... Things there might be outdated.
You can check the [Model Zoo](https://github.com/ZhengPeng7/BiRefNet?tab=readme-ov-file#model-zoo) section in README (All the performance X efficiency of each setting). I've uploaded all the things you may need to [my Google Drive](https://drive.google.com/drive/folders/1s2Xe0cjq-2ctnJBR24563yMSCOu4CcxM).
