### ISSUE TITLE
Great work. When will box-based segmentation inference be released?

### ISSUE THREAD

**Issue by YUANMU227** [ZhengPeng7/BiRefNet#36]
Box-based guidance is of great significance for saliency segmentation of specific parts. I saw this item in your TODO list. When will this feature be launched?

**Comment by ZhengPeng7** [comment]
Yeah, I'm trying to spare time for it... I may do a simple version of it in the next few days.

**Comment by ZhengPeng7** [comment]
Hi, @YUANMU227, I made a [colab](https://colab.research.google.com/drive/1B6aKZ3ekcvKMkSBn0N5mCASLUYMp0whK?usp=sharing) with box guidance for BiRefNet inference. You can try it now.
But now, the box info is manually put into the variable `box`, which is not user-friendly.
I'll make a GUI so that it can obtain the box info by drawings and process multiple boxes.

**Comment by ZhengPeng7** [comment]
Sounds like a class-agnostic object detection first, then the BiRefNet to extract the mask of each proposal?
Thanks, that would be really nice!

**Comment by ZhengPeng7** [comment]
Thanks for your efforts.
Problem-1: it's a kind of problem with the definition of what the target is in the box. I also tried SAM with box prompts, where this problem still exists. It's not a technique problem in my mind.
Problem-2: yeah, I did it since it's the simplest way. But `padding to the very small objects instead of only resizing` and `padding + proportional resizing for all objects` could be truly better.

Idea-1: Sure, that's the easiest way to alleviate this problem.
Idea-2: I know the fixed resolution could be a problem. However, I neither have very sufficient GPU resources for extra training. Thus, it might not be possible to do in the near future.
