### ISSUE TITLE
Run the algorithm locally

### ISSUE THREAD

**Issue by luoshuiyue** [ZhengPeng7/BiRefNet#43]
How does the algorithm run locally on 3K data sets? I don't know how to organize data sets, could you provide an example of file organization structure? I couldn't download it because the data set was too big.

**Comment by ZhengPeng7** [comment]
What do you mean about the `3K data sets`? Doing the inference on 3K resolution images? If you want the inference, I recommend trying the `inference single image` colab demo mentioned in README and modifying it into a local version, which should be fewer than 3 lines of codes in your correct venv.

file organization looks like this:
```
~/datasets/
    - dis
        - [DIS5K/General/...]
            - DIS-TR
                - im
                    - *.jpg/*.png/...
                - gt
                    - *.jpg/*.png/...
            - DIS-TE1
                - im
                    - *.jpg/*.png/...
                - gt
                    - *.jpg/*.png/...
            - TR-COD10K
                - im
                    - *.jpg/*.png/...
                - gt
                    - *.jpg/*.png/...
            ...
```
Check the `config.py` for a better look at the organization of these datasets.

**Comment by luoshuiyue** [comment]
Yes, I mean doing the inference on 3K resolution images. I can run `inference single image` and get the result. But I change this line to keep the original resolution:
![1721872661124](https://github.com/user-attachments/assets/ef541e8f-4a73-4aff-89a8-4309fa8fae7d)
Encouter this error：
![1721872661110](https://github.com/user-attachments/assets/71e3b59f-d5cf-462b-b263-35763e6e09e7)
Is there any way to solve this error？

**Comment by ZhengPeng7** [comment]
Hi, that's a common problem for most deep visual models, which have downsampling methods like pooling or convolution. For example, if there are three `pooling2d(2)`, you have to feed images with resolution as integer times of `2 ** 3`; otherwise, resolutions in the encoder and decoder might differ from each.

In our case here, due to the downsampling operations in the backbone, the size of the input tensor must be integral times of `2 ** 5 = 32`, e.g., `32x32`, `160x160`, `768x768`, etc.

**Comment by luoshuiyue** [comment]
Thank you. I get orginal resolution mask using `resize` function.
