### ISSUE TITLE
Releated to finetunning 

### ISSUE THREAD

**Issue by Kaustubh-cpu** [ZhengPeng7/BiRefNet#53]
@ZhengPeng7  

Great work @ZhengPeng7 
 Actually i am facing 2 issue with the code 
 1 .  I have  trained the model with the backbone of swin_tiny on a sample of dataset but while inference i was expecting black and white mask but i am getting some thing like given below image .
 2 . Can you please suggest me which pretrained model should i used to test or finetune on human images .What ever pretrained i am using from the google drive it is giving the error of shape or key mismatch or unable to load checkpoint .....so to test it on Pretrained what configuration do i need to change in the Config 
![1#Accessories#1#Bag#3660693333_61004a731d_o](https://github.com/user-attachments/assets/571a4e30-1f66-4fe6-977a-2abb095ea7e8)

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7  
If there is any solution please suggest me for this

**Comment by ZhengPeng7** [comment]
Hi, @Kaustubh-cpu; I read your issue last week, but something interrupted me, and I forgot it... But to be honest, could you correct the spelling next time😂 No offense, but that's better. I might've read and understood your question and replied before. But be relaxed, I'm always happy to do some help.

1. Could you share your source image with me? That seems a weird result.
2. For human seg, I would suggest using the [BiRefNet-portrait](https://huggingface.co/ZhengPeng7/BiRefNet-portrait), which was trained on many related datasets. You can find all my models on [my Hugging Face page](https://huggingface.co/ZhengPeng7) or choose the model in my [HF space demo](https://huggingface.co/spaces/ZhengPeng7/BiRefNet_demo) to have an easy try on your samples. For the problem of key mismatching, I want you to know that the default backbone is `SwinL` instead of `SwinT`, which you used before. If the mismatching is something else, please show me and I'll look deeper into it.

**Comment by Kaustubh-cpu** [comment]
![1#Accessories#1#Bag#3660693333_61004a731d_o](https://github.com/user-attachments/assets/916dcfc1-f827-448c-8770-a994f77abd7e)

**Comment by Kaustubh-cpu** [comment]
@ZhengPeng7 

RuntimeError: Error(s) in loading state_dict for BiRefNet:
        Unexpected key(s) in state_dict: "squeeze_module.0.dec_att.aspp1.bn.weight", "squeeze_module.0.dec_att.aspp1.bn.bias", "squeeze_module.0.dec_att.aspp1.bn.running_mean", "squeeze_module.0.dec_att.aspp1.bn.running_var", "squeeze_module.0.dec_att.aspp1.bn.num_batches_tracked", "squeeze_module.0.dec_att.aspp_deforms.0.bn.weight", "squeeze_module.0.dec_att.aspp_deforms.0.bn.bias", "squeeze_module.0.dec_att.aspp_deforms.0.bn.running_mean", "squeeze_module.0.dec_att.aspp_deforms.0.bn.running_var", "squeeze_module.0.dec_att.aspp_deforms.0.bn.num_batches_tracked", "squeeze_module.0.dec_att.aspp_deforms.1.bn.weight", "squeeze_module.0.dec_att.aspp_deforms.1.bn.bias", "squeeze_module.0.dec_att.aspp_deforms.1.bn.running_mean", "squeeze_module.0.dec_att.aspp_deforms.1.bn.running_var", "squeeze_module.0.dec_att.aspp_def
        
       Getting this error when i am trying to do the inference on (BiRefNet-portrait-epoch_150.pth)

**Comment by ZhengPeng7** [comment]
Are you sure that your network architecture settings in `config.py` are the same as those in my default ones?

And about the sample above, I tested it with the weights for `general use` to obtain the result:
![截屏2024-08-12 21 31 32](https://github.com/user-attachments/assets/2ab0daf6-76a0-43af-b66e-8becc9e8078b)

And also with the weights for `portrait segmentation` (though it's a bag):
![截屏2024-08-12 21 32 42](https://github.com/user-attachments/assets/6c26675f-5558-46b5-bbb5-ea10bef252a2)

These two results are surely different, but both are reasonable. How did you get your weird results above?
