### ISSUE TITLE
Segmentation or Matting ? Which one is more suitable?

### ISSUE THREAD

**Issue by minushuang** [ZhengPeng7/BiRefNet#93]
hi @ZhengPeng7 ,   I have created a dataset comprising approximately 1 million samples, which includes original images and their corresponding mask images. 

Each mask image has pixel values ranging between [0, 255], where 0 represents the background, 255 represents the foreground, and values between 0 and 255 generally indicate pixels at the edge transition between the foreground and background.

I am looking to find out  whether my dataset is more suitable for training with a matting method or a segmentation method? 

Additionally, from what I have seen in the code, the only difference between the matting and segmentation methodologies appears to be the loss function used during training, with all other aspects being the same. Is my understanding of this correct?

**Comment by ZhengPeng7** [comment]
Hi, @minushuang. If transparency does exist in data, it's better to see it as a matting problem.
If the values on the edges only indicate the transition, like what trimaps do, I think it's not that commonly used in segmentation.

In my framework, yes, the matting task is more of a regression problem; that's why L1 loss is enhanced there instead of IoU/BCE.

**Comment by minushuang** [comment]
Okay, I got it. I will use the matting method for training my dataset. 
(my previous statements was inccurate, the pixel values between 0 and 255 actually represent transparency as you said)
thank you very much.

**Comment by ZhengPeng7** [comment]
You're welcome :)
